setwd("D:\\coursera\\week4 assignment3")
source("best.R")
best("SC", "heart attack")
best("SC", "heart attack")
best("NY", "pneumonia")
best("MD","heart attack")
best("NY", "pneumonia")
best("TX", "heart attack")
best("AK", "pneumonia")
best("TX", "heart failure")
best("MD", "pneumonia")
best("AL", "pneumonia")
best("SC", "heart attack")
best("NY", "pneumonia")
best("AK", "pneumonia")
source("rankhospital.R")
rankhospital("TX", "heart failure", 4)
rankhospital("WA", "pneumonia", 10)
rankhospital("NY", "heart attack", 7)
rankhospital("WA", "heart attack", 7)
rankhospital("NC", "heart attack", "worst")
rankhospital("MD", "heart attack", "worst")
rankhospital("TX", "pneumonia", 10)
rankhospital("MN", "heart attack", 5000)
?nrow
??alphabeta
??alphabet
?order
source("rankall.R")
r <- rankall("heart attack", 4)
r
rankall("heart failure", 10)
rankall("pneumonia", "worst")
as.character(subset(r, state == "HI")$hospital)
head(rankall("heart attack", 20), 10)
tail(rankall("pneumonia", "worst"), 3)
tail(rankall("heart failure"), 10)
r <- rankall("heart failure", 10)
as.character(subset(r, state == "NV")$hospital)
